name: Scrape electricity prices

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '5 * * * *'  # Runs at 5 minutes past every hour

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v4
    - name: Fetch latest data
      run: |-
        DATE=$(date +%Y/%m-%d)
        curl -s "https://www.hvakosterstrommen.no/api/v1/prices/$DATE""_NO1.json" | jq > oslo-el-pris.json
    - name: Commit and push if changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push